### ISSUE TITLE
Is --datadir really necessary?

### ISSUE THREAD

**Issue by luisgiii** [karalabe/geth-sandbox#1]
Hello :-),

thanks for this library in first place!
I'm building an Android application and I'd like to implement Ethereum inside it that's why I'm here hehe

The thing is that I have a few hours working with it and it's easy to use and implement after looking on the projects you shared but... --datadir is really that necessary?
Is there a way to **no** download the whole blockchain to my Android device? I'm trying to not putting that parameter but it's just not working, the application dies.
If it's that necessary could you please explain me why? I'm a newbie into Ethereum but I'd like to contribute to the whole scene by creating applications.

Could it be because I'm using an unstable nightly build?

Thanks in advance for taking the time to answer!
I'll really appreciate your response :-).

**Comment by ligi** [comment]
to not have to download the whole chain you have to wait for light-client support - you can get some info here: https://gitter.im/ethereum/light-client
PS: there are multiple parties I know ( min 3) working on ethereum-apps for android  - IMHO if you really want to help ethereum on android - making a IPFS client for android might be more important - I don't know anyone working on this currently - but IMHO this is needed for a good ethereum experience on android in the future
