### ISSUE TITLE
Geth not running on android emulator

### ISSUE THREAD

**Issue by axelblaze15** [karalabe/geth-sandbox#2]
I am using Android Studio in Windows 10. I have added geth.aar file in my project and the project is building successfully but on emulator ,it is showing "Geth not running" error. Thanks for your time .
Here is the snapshot of error-
![capture](https://cloud.githubusercontent.com/assets/16748015/24058543/7482ab52-0b71-11e7-9fc8-62c740037c7c.PNG)

**Comment by karalabe** [comment]
This is an unsupported repo.
